export const ActionTypes = {
    FETCH_FISH: "FETCH_FISH",
    SET_USER: "SET_USER",
    SET_ITEMS: "SET_ITEMS",
    SET_POST: "SET_POST",
    SELECTED_ITEM: "SELECTED_ITEMS",
    REMOVE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",
    REMOVE_USER: "REMOVE_USER"
};