"""bug pics

Revision ID: 844fe5a9f70d
Revises: 971787a58089
Create Date: 2023-05-30 19:52:41.576907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844fe5a9f70d'
down_revision = '971787a58089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
